### ISSUE TITLE
Bad Request 오류는 무슨 오류인가요..?

### ISSUE THREAD

**Issue by hyangun617** [dc-creator/record-youtube#4]
Traceback (most recent call last):
  File "upload_video.py", line 199, in <module>
    initialize_upload(youtube, args)
  File "upload_video.py", line 125, in initialize_upload
    resumable_upload(insert_request, args.file)
  File "upload_video.py", line 137, in resumable_upload
    status, response = insert_request.next_chunk()
  File "googleapiclient\_helpers.py", line 134, in positional_wrapper
  File "googleapiclient\http.py", line 967, in next_chunk
  File "googleapiclient\http.py", line 172, in _retry_request
  File "oauth2client\transport.py", line 186, in new_request
  File "oauth2client\client.py", line 761, in _refresh
  File "oauth2client\client.py", line 819, in _do_refresh_request
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Bad Request

이런 오류 뜨면서 업로드가 안되는데 무슨 오류인가요..?

**Comment by tasoo-oos** [comment]
@hyangun617 인터넷 문제입니다.
